---
- hosts: webserver
  gather_facts: true
  user: ubuntu
  become: True
  tasks:

    
    - ec2_facts:

 
    - debug: msg= "{{ hostvars[inventory_hostname]['ansible_ec2_instance_id'] }}"

- hosts: webserver 
  gather_facts: True
  connection: local
  vars:
    region: "us-west-2"
  tasks:
    - name: Terminate all instances
      ec2: state='absent'
           region={{ region }}
           instance_ids={{ item }}
           wait=true
      with_items: hostvars[inventory_hostname]['ansible_ec2_instance_id']
