---
- hosts: webserver
  remote_user: ubuntu
  become: true
  tasks:
    - name: installation of apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2


    - name: copy hello_world.html file
      copy: src=/etc/ansible/hello_world.html dest=/var/www/html/ mode=0644


  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
